HAI 
    I HAS A STR ITZ A YARN
    STR R "1234.567"
    VISIBLE STR
    
    STR IS NOW A NUMBAR
    VISIBLE STR
    
    STR IS NOW A NUMBR
    VISIBLE STR
    
    I HAS A DGT ITZ A NUMBAR
    DGT R MAEK "3543" A NUMBR
    DGT R SUM OF DGT AN "0.2314"
    VISIBLE DGT
    
    DGT IS NOW A NUMBR
    DGT R MAEK SMOOSH "1" AN "2" AN "4" AN "." AN "12" AN "112" MKAY A NUMBR
    VISIBLE DGT
    
    
KTHXBYE